# Python version

In [1]:
import fractions
import numpy as np
import RationalAlgebra as ra
from math import factorial
from typing import List

In [2]:
intVector = List[int]

In [3]:
sampleIndices = [-2, -1, 0, 1, 2]
derivativeOrder = 3

In [4]:
def vectorMultiplicand(d: int, N: int) -> intVector:
    c = np.zeros((N, 1))
    c = c.astype(int)
    c[d] = factorial(d)
    return c
def matrixMultiplier(C: intVector, N: int):
    M = np.zeros((N, N))
    M = M.astype(int)
    exponentRange = range(N)
    for i in exponentRange:
        M[:,i] = [C[i]**x for x in exponentRange]
    
    return M

In [5]:
cc = np.zeros(5, dtype=fractions.Fraction)
type(cc[1])

int

In [6]:
testM = matrixMultiplier([-2,-1,0,1,2], 5)
testc = vectorMultiplicand(3,5)
print(testM)
print(testc)

[[ 1  1  1  1  1]
 [-2 -1  0  1  2]
 [ 4  1  0  1  4]
 [-8 -1  0  1  8]
 [16  1  0  1 16]]
[[0]
 [0]
 [0]
 [6]
 [0]]


In [7]:
np.linalg.inv(testM)

array([[-1.00228468e-18,  8.33333333e-02, -4.16666667e-02,
        -8.33333333e-02,  4.16666667e-02],
       [ 0.00000000e+00, -6.66666667e-01,  6.66666667e-01,
         1.66666667e-01, -1.66666667e-01],
       [ 1.00000000e+00, -2.37904934e-16, -1.25000000e+00,
         0.00000000e+00,  2.50000000e-01],
       [-2.29093640e-18,  6.66666667e-01,  6.66666667e-01,
        -1.66666667e-01, -1.66666667e-01],
       [ 1.14546820e-18, -8.33333333e-02, -4.16666667e-02,
         8.33333333e-02,  4.16666667e-02]])

In [8]:
np.round(np.linalg.inv(testM),decimals=3)

array([[-0.   ,  0.083, -0.042, -0.083,  0.042],
       [ 0.   , -0.667,  0.667,  0.167, -0.167],
       [ 1.   , -0.   , -1.25 ,  0.   ,  0.25 ],
       [-0.   ,  0.667,  0.667, -0.167, -0.167],
       [ 0.   , -0.083, -0.042,  0.083,  0.042]])

## Create rational matrix

In [9]:
A = ra.RationalMatrix(testM)
print(A)

[[ 1,  1,  1,  1,  1],
 [-2, -1,  0,  1,  2],
 [ 4,  1,  0,  1,  4],
 [-8, -1,  0,  1,  8],
 [16,  1,  0,  1, 16]]


In [10]:
Ainv = ra.inv(A)
print(Ainv)

[[    0,  1/12, -1/24, -1/12,  1/24],
 [    0,  -2/3,   2/3,   1/6,  -1/6],
 [    1,     0,  -5/4,     0,   1/4],
 [    0,   2/3,   2/3,  -1/6,  -1/6],
 [    0, -1/12, -1/24,  1/12,  1/24]]


In [11]:
L, U, P = ra.lu(A)
print(L)
print(U)

[[     1,      0,      0,      0,      0],
 [  1/16,      1,      0,      0,      0],
 [  -1/8, -14/15,      1,      0,      0],
 [   1/4,    4/5,   -6/7,      1,      0],
 [  -1/2,  -8/15,    4/7,    1/2,      1]]
[[   16,     1,     0,     1,    16],
 [    0, 15/16,     1, 15/16,     0],
 [    0,     0, 14/15,     2,     4],
 [    0,     0,     0,  12/7,  24/7],
 [    0,     0,     0,     0,    12]]


In [12]:
print( L @ U )

[[16,  1,  0,  1, 16],
 [ 1,  1,  1,  1,  1],
 [-2, -1,  0,  1,  2],
 [ 4,  1,  0,  1,  4],
 [-8, -1,  0,  1,  8]]


In [13]:
print( P @ A )

[[16,  1,  0,  1, 16],
 [ 1,  1,  1,  1,  1],
 [-2, -1,  0,  1,  2],
 [ 4,  1,  0,  1,  4],
 [-8, -1,  0,  1,  8]]


In [14]:
print( ra.inv(P) @ L @ U )

[[ 1,  1,  1,  1,  1],
 [-2, -1,  0,  1,  2],
 [ 4,  1,  0,  1,  4],
 [-8, -1,  0,  1,  8],
 [16,  1,  0,  1, 16]]


# Create rational vector

In [15]:
c = ra.RationalVector(testc) * fractions.Fraction(7,11)
cT = ra.RationalVector(testc.transpose())
print(c)
print(cT)

[[    0],
 [    0],
 [    0],
 [42/11],
 [    0]]
[[0, 0, 0, 6, 0]]


In [16]:
print(cT @ c)

[[252/11]]


In [17]:
print(P @ c)

[[    0],
 [    0],
 [    0],
 [    0],
 [42/11]]


In [18]:
print(P * fractions.Fraction(5.))

[[0, 0, 0, 0, 5],
 [5, 0, 0, 0, 0],
 [0, 5, 0, 0, 0],
 [0, 0, 5, 0, 0],
 [0, 0, 0, 5, 0]]


In [19]:
np.ones((5,5)) * np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones((1,5)) * np.zeros((1,5))

array([[0., 0., 0., 0., 0.]])

In [21]:
!python RationalAlgebra.py

Testing


In [22]:
print(P @ ra.identity(5))

[[0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 1, 0]]


In [49]:
!python test_basic.py

................................
----------------------------------------------------------------------
Ran 32 tests in 0.034s

OK


In [24]:
tmpC = ra.RationalVector(np.zeros((5,1)).astype(int))
tmpC.value[2] = fractions.Fraction(3,4)
tmpC.value[4] = fractions.Fraction(9,2)
tmpR = ra.RationalVector(np.zeros((1,5)).astype(int))
tmpR.value[0][2] = fractions.Fraction(5,7)
tmpR.value[0][0] = fractions.Fraction(9,2)
tmpM = ra.RationalMatrix(np.identity(5).astype(int))
tmpM.value[2,4] = fractions.Fraction(11,7)
tmpM.value[1,2] = fractions.Fraction(3,5)
tmpM.value[4,2] = fractions.Fraction(71,3)
print(tmpC)
print(tmpR)
print(tmpM)

[[  0],
 [  0],
 [3/4],
 [  0],
 [9/2]]
[[9/2,   0, 5/7,   0,   0]]
[[   1,    0,    0,    0,    0],
 [   0,    1,  3/5,    0,    0],
 [   0,    0,    1,    0, 11/7],
 [   0,    0,    0,    1,    0],
 [   0,    0, 71/3,    0,    1]]


In [25]:
Ltest,Utest,Ptest = ra.lu(tmpM)
print(tmpM)
print(Ltest)
print(Utest)
print(Ptest)

[[   1,    0,    0,    0,    0],
 [   0,    1,  3/5,    0,    0],
 [   0,    0,    1,    0, 11/7],
 [   0,    0,    0,    1,    0],
 [   0,    0, 71/3,    0,    1]]
[[   1,    0,    0,    0,    0],
 [   0,    1,    0,    0,    0],
 [   0,    0,    1,    0,    0],
 [   0,    0,    0,    1,    0],
 [   0,    0, 3/71,    0,    1]]
[[      1,       0,       0,       0,       0],
 [      0,       1,     3/5,       0,       0],
 [      0,       0,    71/3,       0,       1],
 [      0,       0,       0,       1,       0],
 [      0,       0,       0,       0, 760/497]]
[[1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 0, 0, 1],
 [0, 0, 0, 1, 0],
 [0, 0, 1, 0, 0]]


In [26]:
Ptest.value[4,3]

Fraction(0, 1)

In [27]:
print(ra.inv(Ptest) @ Ltest @ Utest)

[[   1,    0,    0,    0,    0],
 [   0,    1,  3/5,    0,    0],
 [   0,    0,    1,    0, 11/7],
 [   0,    0,    0,    1,    0],
 [   0,    0, 71/3,    0,    1]]


In [28]:
print(Ptest @ tmpM)

[[   1,    0,    0,    0,    0],
 [   0,    1,  3/5,    0,    0],
 [   0,    0, 71/3,    0,    1],
 [   0,    0,    0,    1,    0],
 [   0,    0,    1,    0, 11/7]]


In [29]:
print(Ltest @ Utest)

[[   1,    0,    0,    0,    0],
 [   0,    1,  3/5,    0,    0],
 [   0,    0, 71/3,    0,    1],
 [   0,    0,    0,    1,    0],
 [   0,    0,    1,    0, 11/7]]


In [30]:
invMtest = ra.inv(tmpM)
print(invMtest)

[[       1,        0,        0,        0,        0],
 [       0,        1,  63/3800,        0, -99/3800],
 [       0,        0,  -21/760,        0,   33/760],
 [       0,        0,        0,        1,        0],
 [       0,        0,  497/760,        0,  -21/760]]


In [31]:
invMtest.value[0,3]

Fraction(0, 1)

In [32]:
print(Ltest + 4)

[[     5,      4,      4,      4,      4],
 [     4,      5,      4,      4,      4],
 [     4,      4,      5,      4,      4],
 [     4,      4,      4,      5,      4],
 [     4,      4, 287/71,      4,      5]]


In [33]:
tmp1 = ra.RationalVector((10*np.random.rand(1,5)).astype(int))
tmp2 = ra.RationalVector((10*np.random.rand(1,5)).astype(int))
print(tmp1.value)
print(tmp2.value)

[[Fraction(3, 1) Fraction(3, 1) Fraction(6, 1) Fraction(4, 1)
  Fraction(3, 1)]]
[[Fraction(3, 1) Fraction(4, 1) Fraction(2, 1) Fraction(2, 1)
  Fraction(9, 1)]]


In [34]:
print(tmp1 + tmp2)

here3
[[ 6,  7,  8,  6, 12]]
