# Python version

In [1]:
import fractions
import numpy as np
from math import factorial
from typing import List


In [2]:
intVector = List[int]

In [3]:
sampleIndices = [-2, -1, 0, 1, 2]
derivativeOrder = 3

In [4]:
def vectorMultiplicand(d: int, N: int) -> intVector:
    c = np.zeros(N, dtype=fractions.Fraction)
    c = c.astype(int)
    c[d] = factorial(d)
    return c
def matrixMultiplier(C: intVector, N: int):
    M = np.zeros((N, N))
    M = M.astype(int)
    exponentRange = range(N)
    for i in exponentRange:
        M[:,i] = [C[i]**x for x in exponentRange]
    
    return M

In [5]:
cc = np.zeros(5, dtype=fractions.Fraction)
type(cc[1])

int

In [6]:
testM = matrixMultiplier([-2,-1,0,1,2], 5)
#testM[2,3] = 10000001
testc = vectorMultiplicand(3,5)
print(testM)
print(testc)

[[ 1  1  1  1  1]
 [-2 -1  0  1  2]
 [ 4  1  0  1  4]
 [-8 -1  0  1  8]
 [16  1  0  1 16]]
[0 0 0 6 0]


In [7]:
np.linalg.inv(testM)

array([[-1.00228468e-18,  8.33333333e-02, -4.16666667e-02,
        -8.33333333e-02,  4.16666667e-02],
       [ 0.00000000e+00, -6.66666667e-01,  6.66666667e-01,
         1.66666667e-01, -1.66666667e-01],
       [ 1.00000000e+00, -2.37904934e-16, -1.25000000e+00,
         0.00000000e+00,  2.50000000e-01],
       [-2.29093640e-18,  6.66666667e-01,  6.66666667e-01,
        -1.66666667e-01, -1.66666667e-01],
       [ 1.14546820e-18, -8.33333333e-02, -4.16666667e-02,
         8.33333333e-02,  4.16666667e-02]])

## Create rational matrix class

In [8]:
import RationalAlgebra as ra

In [9]:
testMsmall = np.zeros((2,2),dtype=int) + fractions.Fraction()
testMsmall[0,0] = fractions.Fraction(1,1)
testMsmall[1,0] = fractions.Fraction(1,5)
testMsmall[0,1] = fractions.Fraction(3,5)
testMsmall[1,1] = fractions.Fraction(4,5)
testRatM = ra.RationalMatrix(testM)

In [10]:
print(testRatM)

[[ 1,  1,  1,  1,  1],
 [-2, -1,  0,  1,  2],
 [ 4,  1,  0,  1,  4],
 [-8, -1,  0,  1,  8],
 [16,  1,  0,  1, 16]]


In [11]:
testInv = ra.inv(testRatM)
print(testInv)

[[    0,  1/12, -1/24, -1/12,  1/24],
 [    0,  -2/3,   2/3,   1/6,  -1/6],
 [    1,     0,  -5/4,     0,   1/4],
 [    0,   2/3,   2/3,  -1/6,  -1/6],
 [    0, -1/12, -1/24,  1/12,  1/24]]


In [12]:
L, U, ipiv = ra.lu(testRatM)
print(L)
print(U)
print(ipiv)

[[     1,      0,      0,      0,      0],
 [  1/16,      1,      0,      0,      0],
 [  -1/8, -14/15,      1,      0,      0],
 [   1/4,    4/5,   -6/7,      1,      0],
 [  -1/2,  -8/15,    4/7,    1/2,      1]]
[[   16,     1,     0,     1,    16],
 [    0, 15/16,     1, 15/16,     0],
 [    0,     0, 14/15,     2,     4],
 [    0,     0,     0,  12/7,  24/7],
 [    0,     0,     0,     0,    12]]
[4 4 4 4 4]


In [13]:
ra.

AttributeError: module 'RationalAlgebra' has no attribute 'isSquare'